### ISSUE TITLE
SVN - Ottenere conflitti tra due utenti

### ISSUE THREAD

**Issue by mzanella** [EduBic/TOS-DomandeRisposte#10]

**Comment by BottCode** [comment]
Io sta domanda non la capisco...e online non ho trovato aiuti.
Cosa vuol dire poi "tra utenti"? Capisco se mi dici tra rami o files, ma tra utenti no. Forse la domanda è malposta

**Comment by mzanella** [comment]
Secondo me intendeva "simulando due utenti che lavorano". Quindi due copie di una repo e uno che non fa ```svn update``` prima di modificare un file

**Comment by EduBic** [comment]
Concordo con la visione di Marco
