### ISSUE TITLE
SVN - Caricare il repository in Internet

### ISSUE THREAD

**Issue by mzanella** [EduBic/TOS-DomandeRisposte#13]

**Comment by EduBic** [comment]
Per **Linux**:

- Creare una cartella repositories dove inserire tutti i repository in rete e un repository (myrepo):
`svnadmin create /home/USER/svn/repositories/myrepo`

- Aprire il file **myrepo/conf/passwd** e inserire le righe:
`[users]
newuser = userpassword`

- Aprire il file **myrepo/conf/svnserve** e decommentare le righe:
`[general]`
`anon-access = none  # nessuno potrà accedere senza autenticazione`
`auth-access = write  # chi è autenticato ha i permessi di read e write`
`password-db = passwd # password del database del repository`
`realm = myrepo  # stringa per condividere l'autenticazione di altri repository`

- aprire il terminale e dare il comando per far partire un deamon che mette in rete i repository contenuti nella cartella repositories:
`sudo svnserve -d --foreground -r /home/USER/svn/repositories`

- Verificare che il repository **myrepo** risponda digitando su terminale:
`svn checkout svn://127.0.0.1/myrepo` 
oppure
`svn checkout svn://localhost/myrepo`


Per **Windows 10**
- Creare il repository:
`svnadmin create C://svn/repositories/myrepo`

- Creare un service il quale esegue **svnserve.exe** e lavora nella directory C://svn/repository (così facendo tutti i repository creati nella cartella repositories saranno disponibili in rete), seguire le istruzioni del link N.b. usare un terminale con permessi d'amministratore:
[https://subversion.open.collab.net/articles/svnserve-service.htm](url)

- Eseguire le operazioni sui file come spiegato nel procedimento con Linux

- Assicurarsi che il service sia attivo e verificare la presenza dei repositories in rete (assicurarsi di essere nella root del sistema NO "/c/Users" ):
`svn checkout svn://127.0.0.1/myrepo` 
oppure
`svn checkout svn://localhost/myrepo`
